server:
  port: 8091

spring:
  application:
    name: order-service
  datasource:
    url: #URL - Connect TO DB
    username: #username- Connect TO DB
    password: #passwd - Connect TO DB
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  eureka:
    instance:
      hostname: localhost
    client:
      server-url:
        defaultZone: http://localhost:8761/eureka/